# This is a basic workflow to help you get started with Actions

name: Docker CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update SHA
        run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/src/_meta

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build -t alexaxms/inrad-app:$(echo $GITHUB_SHA | head -c7) .

      - name: Docker push
        run: docker push alexaxms/inrad-app:$(echo $GITHUB_SHA | head -c7)
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        repository: alexaxms/inrad-app-infra
        token: ${{ secrets.GH_TOKEN }}

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.6.1"

    - name: Update Kubernetes resources
      run: cd ./prod && kustomize edit set image alexaxms/inrad-app:$(echo $GITHUB_SHA | head -c7)
    
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Publish new version $(echo $GITHUB_SHA | head -c7)"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        repository: alexaxms/inrad-app-infra
    
         

